package ao.consuma.aqui.core.navigation

object NavigationTestTags {
    const val HOME = "home_screen"
    const val SEARCH = "search_screen"
    const val ORDERS = "orders_screen"
    const val MORE = "more_screen"
    const val SETTINGS = "settings_screen"
    const val HELP = "help_screen"
    const val ABOUT = "about_screen"
    const val DESIGN_SYSTEM_CATALOG = "design_system_catalog"
    const val INITIALIZATION = "initialization_screen"
    const val SPLASH = "splash_screen"
    const val BOTTOM_NAVIGATION = "bottom_navigation"
    const val BOTTOM_NAV_HOME = "bottom_nav_home"
    const val BOTTOM_NAV_SEARCH = "bottom_nav_search"
    const val BOTTOM_NAV_ORDERS = "bottom_nav_orders"
    const val BOTTOM_NAV_MORE = "bottom_nav_more"
    const val APP_SHELL = "app_shell"

    const val ONBOARDING = "onboarding_screen"
    const val ONBOARDING_PAGE = "onboarding_page"
    const val ONBOARDING_CONTINUE = "onboarding_continue"
    const val ONBOARDING_SKIP = "onboarding_skip"
    const val ONBOARDING_START = "onboarding_start"
    const val ONBOARDING_INDICATOR = "onboarding_indicator"

    const val LOCATION_SETUP = "location_setup_screen"
    const val LOCATION_USE_CURRENT = "location_use_current"
    const val LOCATION_CHOOSE_MANUALLY = "location_choose_manually"
    const val LOCATION_SKIP = "location_skip"
    const val LOCATION_CONFIRM = "location_confirm"
    const val LOCATION_CHOOSE_ANOTHER = "location_choose_another"
    const val LOCATION_SEARCH_FIELD = "location_search_field"
    const val LOCATION_LIST = "location_list"
    const val LOCATION_LIST_ITEM = "location_list_item"
    const val LOCATION_DETECTING = "location_detecting"
    const val LOCATION_DETECTED = "location_detected"
    const val LOCATION_SETTINGS = "location_settings_screen"
    const val LOCATION_SETTINGS_CHANGE = "location_settings_change"
    const val LOCATION_SETTINGS_REMOVE = "location_settings_remove"

    const val HOME_LOCATION_CARD = "home_location_card"
    const val HOME_CHANGE_LOCATION = "home_change_location"
    const val HOME_CHOOSE_LOCATION = "home_choose_location"
    const val HOME_SEARCH = "home_search"
    const val HOME_CATEGORY = "home_category"
    const val HOME_MERCHANT = "home_merchant"
    const val HOME_REFRESH = "home_refresh"
    const val HOME_REFRESHING = "home_refreshing"
    const val HOME_LOADING = "home_loading"
    const val HOME_EMPTY = "home_empty"
    const val HOME_ERROR = "home_error"
    const val HOME_OFFLINE = "home_offline"
    const val MERCHANT_PLACEHOLDER = "merchant_placeholder"
    const val MORE_LOCATION = "more_location"
}
